//! The `oyvey.lock` lockfile.
//!
//! Cargo-inspired TOML. Every resolved package records the exact git revision
//! it was built from and a SHA-256 checksum of its manifest, so a build is
//! reproducible and `oyvey audit` can detect a tampered or hand-edited
//! dependency.
//!
//! ```toml
//! # This file is automatically @generated by Oyvey.
//! # It is not intended for manual editing.
//! version = 1
//!
//! [[package]]
//! name = "rak-net"
//! version = "0.2.1"
//! source = "git+https://github.com/user/rak-net#0123456789abcdef0123456789abcdef01234567"
//! checksum = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
//! ```

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::path::Path;

use crate::LOCK_VERSION;

/// A single resolved package in the lockfile.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct LockEntry {
    /// The package name (from its own `package.rak` `let name`).
    pub name: String,
    /// The version declared in the package's manifest.
    pub version: String,
    /// `git+https://github.com/user/repo#<full-rev>`.
    pub source: String,
    /// SHA-256 hex of the package's `package.rak`.
    pub checksum: String,
}

/// The parsed lockfile.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct LockFile {
    /// Lockfile format version.
    pub version: i64,
    /// Resolved packages, kept sorted by name (Cargo.lock ordering).
    pub package: Vec<LockEntry>,
}

/// A default lockfile already carries the current format version. Deriving
/// `Default` instead would write `version = 0` into every generated lockfile,
/// which reads as "a lockfile from before lockfiles existed" to anything
/// inspecting it later.
impl Default for LockFile {
    fn default() -> Self {
        LockFile {
            version: LOCK_VERSION,
            package: vec![],
        }
    }
}

impl LockFile {
    /// Look up an entry by package name.
    pub fn get(&self, name: &str) -> Option<&LockEntry> {
        self.package.iter().find(|e| e.name == name)
    }

    /// Insert or replace an entry by name, keeping the list sorted.
    pub fn upsert(&mut self, entry: LockEntry) {
        if let Some(slot) = self.package.iter_mut().find(|e| e.name == entry.name) {
            *slot = entry;
        } else {
            self.package.push(entry);
            self.package.sort_by(|a, b| a.name.cmp(&b.name));
        }
    }

    /// Remove an entry by name.
    pub fn remove(&mut self, name: &str) -> bool {
        let before = self.package.len();
        self.package.retain(|e| e.name != name);
        self.package.len() != before
    }

    /// Entries as a name-keyed map (for resolution).
    pub fn by_name(&self) -> BTreeMap<String, &LockEntry> {
        self.package.iter().map(|e| (e.name.clone(), e)).collect()
    }
}

/// Load a lockfile. A missing file yields an empty lockfile (nothing locked
/// yet); a present-but-unreadable file is an error.
pub fn load_lock(path: &Path) -> Result<LockFile> {
    if !path.exists() {
        return Ok(LockFile::default());
    }
    let s = std::fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))?;
    let lock: LockFile =
        toml::from_str(&s).with_context(|| format!("parsing {}", path.display()))?;
    Ok(lock)
}

/// Write a lockfile atomically (write to a temp file, then rename).
pub fn save_lock(path: &Path, lock: &LockFile) -> Result<()> {
    let mut out = String::new();
    out.push_str("# This file is automatically @generated by Oyvey.\n");
    out.push_str("# It is not intended for manual editing.\n");
    let body = toml::to_string(lock).context("serializing oyvey.lock")?;
    out.push_str(&body);
    if let Some(parent) = path.parent() {
        if !parent.as_os_str().is_empty() {
            std::fs::create_dir_all(parent)
                .with_context(|| format!("creating {}", parent.display()))?;
        }
    }
    let tmp = path.with_extension("lock.tmp");
    std::fs::write(&tmp, out).with_context(|| format!("writing {}", tmp.display()))?;
    std::fs::rename(&tmp, path).with_context(|| format!("renaming {}", path.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn roundtrip() {
        let mut lock = LockFile::default();
        assert_eq!(lock.version, LOCK_VERSION);
        lock.upsert(LockEntry {
            name: "b".into(),
            version: "1.0.0".into(),
            source: "git+https://github.com/u/b#bbbb".into(),
            checksum: "cc".into(),
        });
        lock.upsert(LockEntry {
            name: "a".into(),
            version: "0.1.0".into(),
            source: "git+https://github.com/u/a#aaaa".into(),
            checksum: "dd".into(),
        });
        // Kept sorted by name.
        assert_eq!(lock.package[0].name, "a");
        assert_eq!(lock.package[1].name, "b");
        assert!(lock.get("a").is_some());
        assert!(lock.get("missing").is_none());

        let s = toml::to_string(&lock).unwrap();
        let back: LockFile = toml::from_str(&s).unwrap();
        assert_eq!(back.package.len(), 2);
        assert_eq!(back.get("a").unwrap().checksum, "dd");
    }
}
