//! Project discovery, vendoring, and scaffolding.

use anyhow::{bail, Context, Result};
use std::path::{Path, PathBuf};

use crate::lock::LockFile;
use crate::manifest::{Manifest, ENTRY_DEFAULT, ENTRY_LIB, MANIFEST_FILE};
use crate::resolve::Resolved;
use crate::{LOCK_FILE, PACKAGES_DIR};

/// Walk up from `start` looking for a `package.rak`. Returns the project root.
pub fn find_project_root(start: &Path) -> Result<PathBuf> {
    let abs = if start.is_absolute() {
        start.to_path_buf()
    } else {
        std::env::current_dir()
            .context("locating current directory")?
            .join(start)
    };
    let mut cur: Option<&Path> = Some(abs.as_path());
    while let Some(dir) = cur {
        if dir.join(MANIFEST_FILE).is_file() {
            return Ok(dir.to_path_buf());
        }
        cur = dir.parent();
    }
    bail!(
        "no {} found in {} or any parent directory",
        MANIFEST_FILE,
        start.display()
    )
}

/// The directory where dependencies are vendored: `<root>/packages`.
pub fn packages_dir(root: &Path) -> PathBuf {
    root.join(PACKAGES_DIR)
}

/// The lockfile path for a project root.
pub fn lock_path(root: &Path) -> PathBuf {
    root.join(LOCK_FILE)
}

/// Vendor every resolved package into `<root>/packages/<name>/`.
///
/// Each package is copied fresh from its exported checkout (so a re-install
/// is deterministic), and the `.git` directory is never copied. Stale
/// vendored packages that are no longer dependencies are removed.
pub fn vendor_packages(root: &Path, resolved: &[Resolved]) -> Result<()> {
    let dir = packages_dir(root);
    std::fs::create_dir_all(&dir).with_context(|| format!("creating {}", dir.display()))?;

    // Remove vendored packages no longer in the resolve set.
    let keep: std::collections::HashSet<&str> = resolved.iter().map(|r| r.name.as_str()).collect();
    if let Ok(entries) = std::fs::read_dir(&dir) {
        for entry in entries.flatten() {
            let name = entry.file_name().to_string_lossy().to_string();
            if !keep.contains(name.as_str()) {
                let path = entry.path();
                if path.is_dir() {
                    std::fs::remove_dir_all(&path).ok();
                } else {
                    std::fs::remove_file(&path).ok();
                }
            }
        }
    }

    for r in resolved {
        let dest = dir.join(&r.name);
        if dest.exists() {
            std::fs::remove_dir_all(&dest)
                .with_context(|| format!("replacing {}", dest.display()))?;
        }
        if let Some(parent) = dest.parent() {
            std::fs::create_dir_all(parent)
                .with_context(|| format!("creating {}", parent.display()))?;
        }
        copy_dir(&r.checkout, &dest)
            .with_context(|| format!("vendoring {} -> {}", r.checkout.display(), dest.display()))?;
        write_entry_shim(&dest, &r.manifest)?;
    }
    Ok(())
}

/// Make the vendored package importable by its name.
///
/// `rakc` resolves a bare `import <name>` by looking for `<name>.rak` and then
/// `<name>/init.rak` on the search path. A package whose manifest points at a
/// single file (`lib.rak`, say) satisfies neither: its tree is vendored at
/// `packages/<name>/`, but there is no `init.rak` to run. So one is generated,
/// re-exporting whatever the manifest declares as the entry point.
///
/// The package's own tree is left untouched, so a package that already is a
/// directory package (`init.rak` at its root) keeps the `init.rak` it shipped
/// and no shim is written — replacing it would shadow the real one.
fn write_entry_shim(dest: &Path, manifest: &Manifest) -> Result<()> {
    // Resolve the entry the same way a project does, so a package that does
    // not spell out `entry` still gets a usable shim.
    let entry = manifest.resolved_entry(dest);
    if entry.is_empty() || entry == "init.rak" {
        return Ok(());
    }
    // Only shim an entry that actually shipped.
    if !dest.join(&entry).is_file() {
        return Ok(());
    }
    let shim = dest.join("init.rak");
    if shim.is_file() {
        return Ok(());
    }
    let body = format!(
        "// Generated by oyvey. Re-exports the entry point declared in {}.\n\
         // The package's real module lives in ./{}; this file only exists so\n\
         // that `import {}` resolves to a directory package.\n\
         pub from \"./{}\" import *\n",
        MANIFEST_FILE, entry, manifest.name, entry
    );
    std::fs::write(&shim, body).with_context(|| format!("writing {}", shim.display()))?;
    Ok(())
}

/// Recursively copy `src` into `dst`, skipping `.git`.
fn copy_dir(src: &Path, dst: &Path) -> Result<()> {
    std::fs::create_dir_all(dst).with_context(|| format!("creating {}", dst.display()))?;
    for entry in std::fs::read_dir(src).with_context(|| format!("reading {}", src.display()))? {
        let entry = entry?;
        let name = entry.file_name();
        if name == ".git" {
            continue;
        }
        let from = entry.path();
        let to = dst.join(&name);
        if from.is_dir() {
            copy_dir(&from, &to)?;
        } else {
            std::fs::copy(&from, &to)
                .with_context(|| format!("copying {} -> {}", from.display(), to.display()))?;
        }
    }
    Ok(())
}

/// Generate a brand-new project at `path` with `oyvey new`.
pub fn scaffold_new(path: &Path, name: &str, lib: bool) -> Result<()> {
    if path.exists()
        && std::fs::read_dir(path)
            .map(|mut d| d.next().is_some())
            .unwrap_or(false)
    {
        bail!("directory {} is not empty", path.display());
    }
    std::fs::create_dir_all(path).with_context(|| format!("creating {}", path.display()))?;

    let entry = if lib { ENTRY_LIB } else { ENTRY_DEFAULT };
    let entry_path = path.join(entry);
    if let Some(parent) = entry_path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating {}", parent.display()))?;
    }

    let manifest = manifest_template(name, "", "", entry);
    std::fs::write(path.join(MANIFEST_FILE), manifest)
        .with_context(|| format!("writing {}", path.join(MANIFEST_FILE).display()))?;

    std::fs::write(&entry_path, entry_template(name, lib))
        .with_context(|| format!("writing {}", entry_path.display()))?;

    let tests_dir = path.join("tests");
    std::fs::create_dir_all(&tests_dir)
        .with_context(|| format!("creating {}", tests_dir.display()))?;
    let test_path = tests_dir.join("main.rak");
    std::fs::write(&test_path, test_template(name))
        .with_context(|| format!("writing {}", test_path.display()))?;

    std::fs::write(path.join(".gitignore"), gitignore_template())?;
    std::fs::write(path.join("README.md"), readme_template(name))?;
    Ok(())
}

/// Initialize an existing directory with `oyvey init`: write a manifest (if
/// missing) and an entry point (if missing). Never overwrites.
pub fn scaffold_init(root: &Path, name: &str, lib: bool) -> Result<()> {
    let manifest_path = root.join(MANIFEST_FILE);
    if !manifest_path.exists() {
        let entry = if lib { ENTRY_LIB } else { ENTRY_DEFAULT };
        let manifest = manifest_template(name, "", "", entry);
        std::fs::write(&manifest_path, manifest)
            .with_context(|| format!("writing {}", manifest_path.display()))?;
    }
    let entry = if lib { ENTRY_LIB } else { ENTRY_DEFAULT };
    let entry_path = root.join(entry);
    if !entry_path.exists() {
        if let Some(parent) = entry_path.parent() {
            std::fs::create_dir_all(parent)
                .with_context(|| format!("creating {}", parent.display()))?;
        }
        std::fs::write(&entry_path, entry_template(name, lib))
            .with_context(|| format!("writing {}", entry_path.display()))?;
    }
    Ok(())
}

fn manifest_template(name: &str, description: &str, license: &str, entry: &str) -> String {
    format!(
        "let name = \"{name}\"\nlet version = \"0.1.0\"\nlet description = \"{description}\"\nlet license = \"{license}\"\nlet entry = \"{entry}\"\nlet deps = {{}}\n",
        name = name,
        description = description,
        license = license,
        entry = entry,
    )
}

fn entry_template(name: &str, lib: bool) -> String {
    if lib {
        format!(
            "// {name} - a Rak library.\n// Generated by `oyvey new --lib`.\n\npub fn add(a: int, b: int) -> int {{\n    return a + b\n}}\n",
            name = name
        )
    } else {
        format!(
            "// {name} - entry point.\n// Generated by `oyvey new`. Run with: oyvey run\n\ndump \"Hello, World\"\n\nfn main(argv) -> int {{\n    return 0\n}}\n",
            name = name
        )
    }
}

fn test_template(name: &str) -> String {
    format!(
        "// Tests for {name}. Run with: oyvey test\n\ntest \"addition works\" {{\n    assert 1 + 1 == 2\n}}\n",
        name = name
    )
}

fn gitignore_template() -> String {
    "/target\n/packages\n*.exe\n".to_string()
}

fn readme_template(name: &str) -> String {
    format!(
        "# {name}\n\nA Rak project managed by [Oyvey](https://github.com/louiml/oyvey).\n\n## Commands\n\n```bash\noyvey run      # run the entry point\noyvey test     # run the tests\noyvey build    # build a standalone executable\noyvey add user/repo   # add a GitHub dependency\n```\n",
        name = name
    )
}

/// Load the manifest for a project root.
pub fn load_manifest(root: &Path) -> Result<Manifest> {
    let path = root.join(MANIFEST_FILE);
    let content =
        std::fs::read_to_string(&path).with_context(|| format!("reading {}", path.display()))?;
    crate::manifest::parse_manifest_str(&content)
        .map_err(|e| anyhow::anyhow!("{}: {}", path.display(), e))
}

/// Load the lockfile for a project root (empty if missing).
pub fn load_lock(root: &Path) -> Result<LockFile> {
    crate::lock::load_lock(&lock_path(root))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn scaffold_new_creates_buildable_project() {
        let dir = std::env::temp_dir().join(format!("oyvey_scaffold_{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        scaffold_new(&dir, "demo", false).unwrap();

        assert!(dir.join(MANIFEST_FILE).is_file());
        assert!(dir.join("src/main.rak").is_file());
        assert!(dir.join("tests/main.rak").is_file());
        assert!(dir.join(".gitignore").is_file());
        assert!(dir.join("README.md").is_file());

        let m = load_manifest(&dir).unwrap();
        assert_eq!(m.name, "demo");
        assert_eq!(m.entry, "src/main.rak");
        assert!(m.deps.is_empty());
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn scaffold_new_refuses_non_empty_dir() {
        let dir = std::env::temp_dir().join(format!("oyvey_scaffold_ne_{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("file.txt"), "x").unwrap();
        assert!(scaffold_new(&dir, "demo", false).is_err());
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn scaffold_init_does_not_overwrite() {
        let dir = std::env::temp_dir().join(format!("oyvey_init_{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join(MANIFEST_FILE), "let name = \"keepme\"\n").unwrap();
        scaffold_init(&dir, "ignored", false).unwrap();
        let m = load_manifest(&dir).unwrap();
        assert_eq!(m.name, "keepme");
        let _ = std::fs::remove_dir_all(&dir);
    }
}
